### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [brian-zZZ/PDI_fusionner#1]
Hi there,

I have two questions:

1 - I searched by the paper's name but I haven't yet found a link, so can you please help me with that?
2- It's not quite clear how I could use this model for prediction, what kind of output does the model takes, is it only the SMILES? and what's the expected range for the output?

**Comment by brian-zZZ** [comment]
Hi,
Thank you for your inquiry. Our paper is currently undergoing review and is not yet accessible. However, once it is available, you will be able to find the answers to your questions in the released paper. We appreciate your patience during this process and will notify you once our paper is accessible.
Best regards.

**Comment by brian-zZZ** [comment]
> Hi there,
> 
> I have two questions:
> 
> 1 - I searched by the paper's name but I haven't yet found a link, so can you please help me with that? 2- It's not quite clear how I could use this model for prediction, what kind of output does the model takes, is it only the SMILES? and what's the expected range for the output?

Hi,
Thank you for your inquiry. Our paper is currently undergoing review and is not yet accessible. However, once it is available, you will be able to find the answers to your questions in the released paper. We appreciate your patience during this process and will notify you once our paper is accessible.
Best regards.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
Thank you for your response @brian-zZZ .
I wish you all the luck with the review of your paper :)
